### ISSUE TITLE
tasks command

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling-sbt-plugin-demo#4]
Is it worth adding the sbt task command to the documentation, so users can view a list of all the available commands? I know the documentation is moving, but people are still going to be using this README.

**Comment by pdalpra** [comment]
Well, could be worth it.
But I'm not sure we should add go beyond that on documenting tasks/commands that are SBT builtins.
After all, this project is meant to showcase Gatling's SBT Plugin, not SBT itself.

**Comment by aidylewis** [comment]
Point taken, but if we run 'tasks' on this project, it shows all the new stuff you've done (not just SBT builtins). I'd replace 'tasks' with the 'lastReport' section. Maybe even a link in the README that points to the official documentation regarding this plugin.

**Comment by pdalpra** [comment]
Indeed, `tasks` make sense.
Since you have a PR where you added tasks to the README, would you mind rebasing it ?
I'll merge it after your rebase :)

**Comment by aidylewis** [comment]
I deleted the fork. Can you reject the PR and I'll create a new one?

**Comment by pdalpra** [comment]
Sure :)
