### ISSUE TITLE
target jdk 8?

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling-sbt-plugin-demo#6]
Should we add a target of jdk 8 and point users to the Oracle install in the README?

**Comment by pdalpra** [comment]
As long as Gatling itself doesn't target JDK8, no :)

**Comment by aidylewis** [comment]
I've compiled my tests using JDK8.  This is something we should be pushing users towards.

**Comment by pdalpra** [comment]
I agree, and I also use JDK 8 as my default JDK too, and we generally recommand to use the latest JDK.
But we can't force users to use JDK 8 in this demo as long as it is not a prerequisite for running Gatling.

**Comment by aidylewis** [comment]
OK agreed. I am now pointing to this repo from my [repo](https://github.com/bbc/gatling-load-tests#getting-started).
